### ISSUE TITLE
osm-search fails with set: Wrong type argument: listp, t

### ISSUE THREAD

**Issue by root42** [minad/osm#1]
Using GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10) of 2020-09-19 in Ubuntu, I can't use osm-search. It results in the above error. osm-home works fine, and I can zoom and move the map around. However searches, while giving back results, give the wrong type argument error once I select a result.

**Comment by minad** [comment]
Thanks for the report.

**Comment by root42** [comment]
Current version in MELPA, v0.3, is not fixing it, sorry.

**Comment by root42** [comment]
Upgraded again today, and now it works! Thanks, I think this bug is truly solved now.
