### ISSUE TITLE
Support EAF?

### ISSUE THREAD

**Issue by manateelazycat** [minad/osm#10]
Hi there,

Your project is looks exciting, do you think about using [EAF](https://github.com/emacs-eaf/emacs-application-framework/) to display a OpenStreetMap?

I'm author of EAF, I will provide some help if you want to support EAF. ;)

**Comment by minad** [comment]
Thanks! I want to use the Emacs built-in facilities. Osm.el has no dependencies beside Emacs with SVG and XML support and curl.

**Comment by manateelazycat** [comment]
ok thanks for reply

**Comment by AkibAzmain** [comment]
@manateelazycat: I think you can write a separate package for integrating `osm.el` into EAF.

By the way, EAF is awesome.  But I think using GTK would have been better, since Emacs uses GTK.  But obviously the killer feature is asynchronous execution.  I wish Emacs had this feature.
