### ISSUE TITLE
OSM fails when Emacs not built with json support

### ISSUE THREAD

**Issue by ericsfraga** [minad/osm#11]
As my system did not have the libjansson library, Emacs had been built without json support. In this case, searching does not work and returns with an error message indicating that json-parse-string is not known.
I solved my problem by installing the library and rebuilding Emacs. However, on the emacs.help newsgroup, it has been suggested that osm should fall back on json-read-from-string when json-parse-string is not available.

**Edit**: forgot to add that I'm really liking this package!

**Comment by minad** [comment]
Thanks! I just checked Emacs 27 of Debian and it comes with `json-parse-string` support, so it seems commonly available. The same issue exists with libxml support which provides its own entry point which is incompatible from xml.el. There is also no fallback there. Overall osm.el requires a full-featured Emacs (libxml, librsvg, libpng, libjpg), so it is not a big deal to also require libjansson. I think it is therefore okay to not fall back to `json-read-from-string` from json.el. Basically the decision to not fallback has been made by the API designers of Emacs. I wonder why they made this decision and did not redirect `json-parse-string` to `json-read-from-string` - performance reasons and/or correctness issues? Maybe the idea is to phase out json.el.

**Comment by ericsfraga** [comment]
I think you have the correct approach: require json support natively in Emacs. At least on Debian, it's easy enough to install the jansson library and build Emacs. I have no idea, however, what other systems may be like in this regard.
Thank you.

**Comment by minad** [comment]
> At least on Debian, it's easy enough to install the jansson library and build Emacs.

Emacs 27 comes ootb with jansson. There is no need to compile Emacs yourself. See https://packages.debian.org/buster-backports/emacs-gtk.

**Comment by ericsfraga** [comment]
Yeah, I'm using Emacs v29.x (tracking git repository for fun ;-)).

**Comment by minad** [comment]
The compat library always provides `json-parse-string`, see https://git.sr.ht/~pkal/compat.
