### ISSUE TITLE
Add fallback in case json-parse-string is absent?

### ISSUE THREAD

**Issue by oantolin** [minad/osm#15]
My Emacs doesn't have te newer json-parse-string function, but I could use the osm search functionality with the following definition:

```elisp
(defun json-parse-string (json &rest _)
  (json-read-from-string json))
```

(I thought I might need to convert arrays to lists in the return value, since you use `:array-type 'list`, but it seems to work as-is.)

Maybe osm could detect the lack of `json-parse-string` and use `json-read-from-string` instead?

**Comment by minad** [comment]
Hi Omar, I am glad that you try out my package! Be aware of bugs and instabilities. See #11 for a reasoning why no such fallback exists yet. I wonder if the absence of the API is common. It is at least present on Debian Emacs 27 builds, which I consider as somewhat representative. It is unclear to me what the Emacs maintainer intended here. Should every package try all the APIs in sequence until one is available. This does not seem like an acceptable long-term solution to me.

**Comment by minad** [comment]
I just checked the Emacs 27 changelog: **The option is on by default.**

> The new configure option '--with-json' adds native support for JSON.
This uses the Jansson library.  The option is on by default; use
'./configure --with-json=no' to build without Jansson support.  The
new JSON functions 'json-serialize', 'json-insert',
'json-parse-string', and 'json-parse-buffer' are typically much faster
than their Lisp counterparts from json.el.

**Comment by minad** [comment]
I dug a bit deeper. `json-parse-string` has a single occurence in the Emacs code base:

https://github.com/emacs-mirror/emacs/blob/6b923a5ebc6b2183fd2d7be54e1804bb088d59ed/lisp/progmodes/python.el#L2379-L2389

I don't think that's a good solution if every package has to add such a workaround/wrapper. On the other hand when I looked at libxml/eww, I found this:

https://github.com/emacs-mirror/emacs/blob/6b923a5ebc6b2183fd2d7be54e1804bb088d59ed/lisp/net/shr.el#L294-L304

Overall I am not sure if I should stick to an uncompromising and not so pragmatic point of view here. :-P

**Comment by oantolin** [comment]
The package is fantastic, very responsive! (But of course that's exactly what I expected.) And apparently OSM's coverage of Mexico City is quite good.

I'm aware I have pretty weird Emacs builds. :) I hope the Emacs maintainers' plan isn't for every usage of the json functions to have to check which functions the user actually has!

I think it's fine for you to say that `osm` uses `json-parse-string` and to document that users that don't have it can just define the function in their personal configuration. I believe the following is a correct implementation in terms of the older API:

```elisp
(cl-defun json-parse-string (string &key
                                    (object-type 'hash-table)
                                    (array-type 'array)
                                    (null-object :null)
                                    (false-object :false))
  (let ((json-object-type object-type)
        (json-array-type (if (eq array-type 'array) 'vector array-type))
        (json-null null-object)
        (json-false false-object)
        (json-key-type nil))
    (json-read-from-string string)))
```

**Comment by oantolin** [comment]
Also, I apologize for neglecting to search for earlier issues! I would have found #11.

**Comment by minad** [comment]
Thanks! 

> And apparently OSM's coverage of Mexico City is quite good.

Yes, densely populated areas are usually covered very well. I really like osm. I've used it for years but never really contributed anything. So at least an Emacs package this time. :)

You can also get aerial imagery in case you need this via maptiler: https://github.com/minad/osm/wiki#additional-tile-servers.
The resolution is bad for rural areas but big cities seem to have better images. I should probably not tell you this to not hurt your freedom since maptiler seems to be a commercial service. :-P

> I think it's fine for you to say that osm uses json-parse-string and to document that users that don't have it can just define the function in their personal configuration. I believe the following is a correct implementation in terms of the older API:

Great, thanks! I will point users to that implementation if the issue comes up more often. This remains to be seen. But for example Lsp users also like to use the fast json functionality and Lsp seems to be quite popular.

**Comment by minad** [comment]
The compat library always provides json-parse-string if it is missing from Emacs, see https://git.sr.ht/~pkal/compat.
