### ISSUE TITLE
Possible to browse OpenRailwayMap?

### ISSUE THREAD

**Issue by scfc** [minad/osm#18]
`osm-server-list` does not have a predefined entry for [OpenRailwayMap](https://www.openrailwaymap.org/).  Can `osm` be used to browse OpenRailwayMap?

**Comment by minad** [comment]
OpenRailwayMap is not a base tile layer, see https://a.tiles.openrailwaymap.org/standard/1/0/0.png. Osm.el doesn't support merging bitmap tiles yet. We could add this in the future and also displaying route overlays (as vector data). Help is welcome.

**Comment by scfc** [comment]
Thanks for the information.  It would be very nice if someone could implement that.
