### ISSUE TITLE
command-execute: Cannot open load file: No such file or directory, osm

### ISSUE THREAD

**Issue by novoid** [minad/osm#2]
Hi,

I just stumbled over your elpa package and tried to test it before I add it to my config. For this, I copied the use-package snippet in an elisp-babel-block of my Org-mode and executed it.

When invoking any osm-* command, I get: `command-execute: Cannot open load file: No such file or directory, osm`. What could that mean? Is there any external dependency I don't get?

**Comment by minad** [comment]
To try the package do the following:

1. M-x package-install osm
2. M-x osm-home

If you like to keep it, add the use-package block to your config if you
use use-update. If you don't use-package you can just bind `osm-home`
for example to a key.

If you don't want to keep it:

1. M-x package-delete osm
2. Delete the tile cache ~/.config/emacs/var/osm/

**Comment by novoid** [comment]
`package-install` returns `package-compute-transaction: Package ‘emacs-27.1’ is unavailable`

I'll look at it tomorrow, maybe purging everything related to osm, restarting Emacs and re-try your commands.

**Comment by novoid** [comment]
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14) of 2020-03-26, modified by Debian

`M-x package-install osm` results in: `package-compute-transaction: Package ‘emacs-27.1’ is unavailable`

It seems to be the case that we've got a dependency on Emacs 27. Maybe you should mention this in the README?

**Comment by minad** [comment]
You can get Emacs 27 on Debian via buster backports. I highly recommend upgrading. Emacs 26 is quite buggy in contrast to Emacs 27 and 28 will be even better.

**Comment by novoid** [comment]
Thanks. I'm running Xubuntu LTS and I'm waiting for the new 22.04 LTS to be prepared for upgrades. I didn't face any Emacs 26 issue so far. I'll retest your promising tool in the autumn.
