### ISSUE TITLE
HiDPI support: Zoom image tiles by a fixed factor

### ISSUE THREAD

**Issue by jypma** [minad/osm#22]
I have a 280DPI screen, making the default font of Mapnik tiles very small. Would it be possible to scale all tiles by a given factor (preferably float, but even 2x would help)? I know org-mode can scale images it shows in-line, so perhaps something can be done.

I'd be happy to try something myself, if someone can nudge me in the right direction.

**Comment by minad** [comment]
Some of the tile servers also provide 512x512 tiles which are meant for HiDPI. So the first step would be to replace all occurences of 256 with a osm--tile-size variable which can then be configured per server. This should be quite easy to do.
