### ISSUE TITLE
FR: add support for find-file gpx files -> use osm-gpx-show 

### ISSUE THREAD

**Issue by mrvdb** [minad/osm#24]
It would be nice if osm could be configured to use osm-gpx-show when opening GPX files with `find-file`. 

I'm thinking something similar as opening PNG and PDF files where a `C-c C-c` binding switches between the rendered view and the source view.

**Comment by mrvdb** [comment]
Quick and dirty impl. of directly showing a gpx track on opening the gpx file.

```
(add-to-list 'auto-mode-alist '("\\.gpx" . osm-mode))

(add-hook 'osm-mode-hook 'osm-maybe-gpx)

(defun osm-maybe-gpx()
  "Runs in osm-mode hook"
  (let* ((file (buffer-file-name)))
    (when (and file (string= (file-name-extension file) "gpx"))
      (osm-home) ;; Needed for a connection to a server?
      (osm-gpx-show (buffer-file-name)))))

It's a bit unclear to me how osm handles files connected to the osm buffer, so switching between gpx "source" and the rendering view is not trivial for me.

**Comment by minad** [comment]
I am not sure I want this. If you open gpx files it is also likely that you want to treat them as xml. I think it is perfectly fine to first switch to an osm buffer and then open the gpx file there.

**Comment by mrvdb** [comment]
fair enough. 

Just to elaborate a bit. I liked the consistency of having 'special files' treated the same. In my workflow that means rendering the file (this applies to svg, png, pdf, ps) and having a quick 'switch to edit' key combo for those files. 

I do not typically edit/create those files manually, but managing the file in their two representations is very comfortable. I guess osm is a tad bit different, as there could be multiple gpx files attached to the render view?
