### ISSUE TITLE
Don't black out while zooming in or out

### ISSUE THREAD

**Issue by AkibAzmain** [minad/osm#26]
While zooming in or out, isn't it possible to scale and show the old images until new ones are downloaded?

**Comment by minad** [comment]
Yes, but zooming ist quite expensive and slow in Emacs. You could try to implement this, but I consider it out of scope.

**Comment by AkibAzmain** [comment]
> Yes, but zooming ist quite expensive and slow in Emacs. You could try to implement this, but I consider it out of scope.

What do you mean by "ist"? Do you mean "isn't" or "is"?

**Comment by minad** [comment]
Sorry, this was my mobile typo correction. I mean it is too expensive so we are not going to add this here. I value responsiveness higher than such eye candy. Usually the tiles load quicky anyway.

**Comment by AkibAzmain** [comment]
> I value responsiveness higher than such eye candy. Usually the tiles load quicky anyway.

I too value responsiveness, but my connection is slow, so it takes about 10-15 seconds on average to load all the tiles (and more than several minutes in worst case).
