### ISSUE TITLE
can osm be used as offline map viewer

### ISSUE THREAD

**Issue by emacs25** [minad/osm#27]
i have my city road map tiles from level 10-16,and i want to use osm.el to view them 

now osm.el only can view online map.i think it is much better to support offline map when necessary.

here is my map directory tree:
```
~/.emacs.d/var/osm/roadmap-offline/10/110/(111-116).jpg
~/.emacs.d/var/osm/roadmap-offline/10/111/(111-116).jpg
..........
..........
~/.emacs.d/var/osm/roadmap-offline/16/22222/(22200-22400).jpg
~/.emacs.d/var/osm/roadmap-offline/16/22422/(22200-22400).jpg
```

thank you!

**Comment by minad** [comment]
Sure. This should already work if you define a custom "server" and put the tiles into the osm tile folder cache in the right format. You also have to make sure that the tile cache is not deleted. See `osm-max-age` (this should maybe generalized per server?).

We could add further support for "servers" without a `:url` field. For such servers no downloads should be started for missing tiles. See `osm--enqueue-download`. PR welcome!
