### ISSUE TITLE
Zoom buttons jump around

### ISSUE THREAD

**Issue by monnier** [minad/osm#29]
As the zoom level changes, the position of the `+/-` buttons to zoom in/out move, so if you just place your mouse on `+` and click a few times, it may zoom in the number of times you clicked if you're lucky but most likely it will end up clicking on something else at some point :-(
I guess the simplest solution is to move the buttons to the left of the "scale witness".

Also, while I'm here: it'd be good to have an entry point that just "shows the map" without any explicit starting location (probably using "0 0 2" as starting point, tho it could also record the last viewed position/zoom).

**Comment by minad** [comment]
> As the zoom level changes, the position of the +/- buttons to zoom in/out move, so if you just place your mouse on + and click a few times, it may zoom in the number of times you clicked if you're lucky but most likely it will end up clicking on something else at some point :-(

This doesn't happen for me. Do you use some weird font settings?

> Also, while I'm here: it'd be good to have an entry point that just "shows the map" without any explicit starting location (probably using "0 0 2" as starting point, tho it could also record the last viewed position/zoom).

Not sure what you are asking about here. You can set the home coordinates and then call `osm-home`. What else do you need?

**Comment by monnier** [comment]
> This doesn't happen for me.

The scale bar changes size for me, yes.

> Do you use some weird font settings?

Define "weird"?
That top bar uses a variable pitch font (probably DejaVu Sans).

I think it also depends on the horizontal size of your window (if it's
wide enough, the stretch space solves the problem).

While I'm here: the "hamburger menu" tends to get hidden beyond the
right edge of the window.  Maybe the "map style" should be moved into
that menu?

>> Also, while I'm here: it'd be good to have an entry point that just "shows
>> the map" without any explicit starting location (probably using "0 0 2" as
>> starting point, tho it could also record the last viewed position/zoom).
> Not sure what you are asking about here. You can set the home coordinates
> and then call `osm-home`. What else do you need?

Ah, I just wasn't aware of `osm-home`.

I'd consolidate `osm-goto` and `osm-home` into an entry point called
`osm` where the `read-string` defaults to "Home" which then uses the
`osm-home` location.  Or something like that.


        Stefan

**Comment by minad** [comment]
Regarding the top bar, I have none of your issues, but I think I also don't use a variable pitch font there. If the hamburger gets hidden it is either a bug of your window manager or of Emacs. Why would Emacs display a menu outside of the screen?

Can you give me a simple recipe on how I can enable variable-pitch for this header line? Then I can add a fix such that it works also in that case.

> I'd consolidate `osm-goto` and `osm-home` into an entry point called
`osm` where the `read-string` defaults to "Home" which then uses the
`osm-home` location.  Or something like that.

I find it more convenient in its current form. Note that you can also use bookmarks as entry points. There are many entry points.

**Comment by monnier** [comment]
The new location of items in the bar fix the problem for me, thanks.  The only minor downside is that the scale-bar at the extreme right doesn't have an "end marker", so I sometimes wonder whether I see all of it, or whether it's truncated because my window is too narrow.

Regarding the entry point, I don't have a problem with having many entry points, but it's just that upon first use it too me a while to guess which command was "the entry point": I ended up choosing `osm-goto` even though I didn't have any location at hand and it took me a bit of thinking to guess a starting location to provide, `osm-home` didn't seem relevant for some reason (I think it sounds like something I'd use from within OSM?).

Indirectly related: why is `osm` a macro rather than a function?

**Comment by monnier** [comment]
>> Indirectly related: why is osm a macro rather than a function?
> In order to result in nicer Elisp links ;)

That was my guess, but all the args it takes are self-quoting anyway, so
the calls would look identical if it were a function, AFAICT.
What am I missing?
Do you have an example link where it makes a difference?

[ FWIW, I'd much rather use URLs for such links and then register `osm`
  as the handler for those URLs.  But for some reason, URLs for world
  locations don't seem very popular (instead people use URLs directly
  to Google Maps or some such :-( ).  I don't even know if there's
  a standard format for "real world URLs".  ]

**Comment by minad** [comment]
> That was my guess, but all the args it takes are self-quoting anyway, so
the calls would look identical if it were a function, AFAICT.
What am I missing? Do you have an example link where it makes a difference?

No, symbols for the server name are not self quoting.

> [ FWIW, I'd much rather use URLs for such links and then register `osm`
  as the handler for those URLs.  But for some reason, URLs for world
  locations don't seem very popular (instead people use URLs directly
  to Google Maps or some such :-( ).  I don't even know if there's
  a standard format for "real world URLs".  ]

That's also a good idea. We could add some URI handler for that. But Elisp links also have some appeal since you can trigger them without any fancy additional integration. I got this weird idea from the eev package ;)

**Comment by monnier** [comment]
>> That was my guess, but all the args it takes are self-quoting anyway, so
> the calls would look identical if it were a function, AFAICT.
> What am I missing? Do you have an example link where it makes a difference?
> No, symbols for the server name are not self quoting.

An extra ' for that one (optional) argument seems to be a very little
price to pay for the benefit of making it a plain old function (which
also makes it possible to make it a command :-)

> That's also a good idea. We could add some URI handler for that.

Do you happen to know of an RFC/W3C standard for "world locations"
defining such URLs?


        Stefan

**Comment by minad** [comment]
> An extra ' for that one (optional) argument seems to be a very little
price to pay for the benefit of making it a plain old function (which
also makes it possible to make it a command :-)

Well, but I never wanted to make this a command. The whole purpose of this macro is for links. I know it is weird :-P

> Do you happen to know of an RFC/W3C standard for "world locations"
defining such URLs?

https://en.wikipedia.org/wiki/Geo_URI_scheme

**Comment by monnier** [comment]
>> An extra ' for that one (optional) argument seems to be a very little
> price to pay for the benefit of making it a plain old function (which
> also makes it possible to make it a command :-)
>
> Well, but I never wanted to make this a command.

Weird.  It's such an obvious name for the main entry point (where you
could accept search strings, bookmark names, and longitude/latitude/zoom
specifications, all from the same entry point :-)

[ BTW, the use of `completing-read` makes it cumbersome to type SPC in
  `osm-search`.  ]

>> Do you happen to know of an RFC/W3C standard for "world locations"
>> defining such URLs?
> https://en.wikipedia.org/wiki/Geo_URI_scheme

Great, thanks.  I'm surprised it's so limited.
I guess it reflects the (relative) lack of use.

Beside registering a handler for it, `osm.el` could also offer a way to
generate such URLs.


        Stefan

**Comment by monnier** [comment]
> I am not such a fan of commands which do everything. How would such
> a command look like, would it offer all these things at the same time via
> completing-read?

Other than for bookmarks completions might not be very useful anyway,
but yes, the completion table would be a combination of the list of
bookmarks and the history of past invocations, I guess.

> The way I designed it now is that we have separate commands,

The `osm` entry point wouldn't need to replace the more specialized
entry points (especially for use from within an OSM buffer).

> mnemonically bound to a C-c m prefix map.

I don't have such a prefix map and I can't see it in the code.
And of course I don't use OSM often enough to remember such key
bindings, whereas I'd remember `M-x osm` :-)

>> [ BTW, the use of `completing-read` makes it cumbersome to type SPC in
>>   `osm-search`.  ]
>
> Oh dear. I recommend to redefine SPC to self-insert-command.

I know how to deal with it, of course.
I'm just pointing out a poor behavior in the default configuration.


        Stefan

**Comment by minad** [comment]
> I don't have such a prefix map and I can't see it in the code.
And of course I don't use OSM often enough to remember such key
bindings, whereas I'd remember `M-x osm` :-)

Hmm. One thing I may be willing to do is alias osm to osm-home. Then one would at least have an easy entry point (no selection, but at least you would see a map right away in contrast to osm-goto). However the osm macro complication remains. Is it possible to write an interactive macro? :)

> I know how to deal with it, of course.
I'm just pointing out a poor behavior in the default configuration.

Of course I know that you. Maybe it is time to change the defaults. I could of course rebind the keys somehow via the minibuffer-setup-hook, but I tend to avoid this. I think it is overall easier to call plain completing-read and then let the completion system handle this instead of adding layers and layers.

**Comment by monnier** [comment]
> Hmm. One thing I may be willing to do is alias osm to osm-home. Then one
> would at least have an easy entry point (no selection, but at least you
> would see a map right away in contrast to osm-goto).

Right.

> However the osm macro complication remains.

That's the issue.

> Is it possible to write an interactive macro? :)

:-(

>> I know how to deal with it, of course.
>> I'm just pointing out a poor behavior in the default configuration.
>
> Of course I know that you. Maybe it is time to change the defaults.

I fully agree that the default binding of SPC in the minibuffer
completion maps should go.  Maybe it's time we try again.

Another option would be for the caller of `completing-read` to indicate
whether it's likely that the users will want to type the SPC character.

Yet another would be for `minibuffer-complete-word` to insert a SPC when
it would otherwise beep with "No match" and `minibuffer--require-match`
is nil (assuming it was invoked via SPC, of course).

None of those will help OSM users on non-future Emacsen, tho.


        Stefan

**Comment by minad** [comment]
> I fully agree that the default binding of SPC in the minibuffer
completion maps should go.  Maybe it's time we try again.

> None of those will help OSM users on non-future Emacsen, tho.

Well, but it is a chicken and egg problem. If I adapt to the default UI then the bad defaults will never change. Generally all my packages work *very well* with the default UI, but I expect users to do minor configurations, e.g., like unbinding SPC.
