### ISSUE TITLE
Zoom looses location indicator

### ISSUE THREAD

**Issue by artelse** [minad/osm#3]
Title says it already, when you zoom in the blue location indicator disappears.

**Comment by minad** [comment]
This is intentional. The blue marker is transient and only visible until the next operation. For example as soon as you start to move around on the map the marker doesn't make much sense anymore. One could consider preserving the marker when zooming but this would be a deviation from the otherwise consistent behavior.

**Comment by artelse** [comment]
I'm unsure about your argument about moving around on or zooming in/out of the map. It does make a lot of sense to have the marker as a location reference, all online maps have this behavior for good reason. Why deviate from expected behavior?

**Comment by minad** [comment]
> all online maps have this behavior for good reason

I don't see this. When I click around in google maps or openstreetmap I don't get any marker when clicking somewhere. You can create bookmarks if you want a location to persist. The transient marker which I have in osm.el has the purpose of temporarily selecting a location or temporarily selecting a bookmark, e.g., for deletion. Anyway, I will keep this design for a little longer to get more experience and to gather more feedback.

**Comment by minad** [comment]
One possible modification of the current behavior could be to preserve the marker as long as the user doesn't click to another location, jump to another location (via search or bookmark). The marker could be preserved when moving and zooming. But what if the marker leaves the visible range?

**Comment by artelse** [comment]
Indeed, moving around or zooming preserves the marker, even when it (temporarily) moves off screen. Clicking to set a new location is of course different.

**Comment by hmelman** [comment]
As mentioned [here](https://github.com/minad/osm/issues/14#issuecomment-1073161203) I also would like the marker to remain through zooms.  I find that Google Maps and Apple Maps behave this way.  If I click and get a marker, as I pan and scroll the map the marker remains, even if it pans off screen, it's there when I pan back to it.  Both of those also have trackpad based zooming that's centered on mouse position; in those uses the marker remains and is quite helpful in letting you see the position as it moves (simultaneously zooming and panning).

I think perhaps the rule should be the marker stays until you explicitly select another location, and even then I'd want a to keep it around to compare the two (or more) positions.  Bookmarks may be it, but I rarely want to persist them between sessions.  I'm more likely to want to want to make a temporary map of interesting locations and screenshot it.

I don't quite understand what you have in mind for the current blue marker. You say it "has the purpose of temporarily selecting a location or temporarily selecting a bookmark, e.g., for deletion"  I can see utility in that, but maybe you want something that behaves more like point in other emacs buffers?  And maybe we're asking for some other kind of marker after an explicit search?
