### ISSUE TITLE
symbol void `osm-mode-map`

### ISSUE THREAD

**Issue by peterbecich** [minad/osm#32]
I see this error:
```
Error (use-package): osm/:catch: Symbol’s value as variable is void: osm-mode-map
```

I have no config for OSM other than
```
(use-package osm :ensure t)
```

The error is also thrown with this configuration: https://github.com/minad/osm#configuration

Thanks

**Comment by minad** [comment]
This is an update issue. Update all packages, inclunding Compat, then reinstall Osm.
