### ISSUE TITLE
Suggestion on keybindings

### ISSUE THREAD

**Issue by BBoal** [minad/osm#36]
First, thanks for sharing your work. Your packages are awesome!

I have a minor suggestion, since I use consult with your suggested bindings, and "C-c m" is already taken, either with "consult-mode-command" or "consult-man", changing the proposed bind keywords in the use-package snippet to "C-c o ..." would match the package name and also avoid errors with consult.

Best regards,
BBoal

**Comment by minad** [comment]
Thanks for the suggestion. In my s`C-c o` is taken by globally-bound Org-related functionality. I have bound `consult-mode-command` to `C-c M-x` and `consult-man` to `C-h h m`. Therefore the `C-c m` suggestion which stands for "map" and is easily memorable.
