### ISSUE TITLE
FEATURE REQUEST: Get osm-search to return the name of item selected

### ISSUE THREAD

**Issue by rswgnu** [minad/osm#37]
If I call osm-search with a partial name match, it shows me completions and allows me to select one but there is presently no return value that shows what got selected.  Since osm--goto is the last call within this function, just have that return the name it is given or nil if none.  Then change osm-goto to not return nil but return the result of osm--goto as well.

Also, if there is a name associated with an osm--goto call, it would be good to see that name on the map display somewhere, e.g. on the modeline or in the minibuffer, without having to move the mouse to hover over the mark on the map highlighting the selection.  Immediate feedback is better.  Thanks.

**Comment by minad** [comment]
Hi Robert, why do you need this? It seems a bit unconventional to return the name from `osm-search` or `osm--goto`. An undefined or nil return value is more natural.

**Comment by rswgnu** [comment]
If I give a partial string for the name and location as input, then I need
to know the full name in the output.  Maybe I want to bookmark or embed a
link to it in another buffer.
Maybe this needs to be a separate, public function that given an input
resolves to a single named output.  -- rsw

**Comment by minad** [comment]
Okay and what do you need this for? osm.el is not really supposed to be a query API for the nominatim geo naming service. Even if osm-search would return the full name or location it would still lead to a jump in the map, which is probably not desired if you want to call this programmatically?

**Comment by minad** [comment]
I extracted a function `osm--search` to search by name. It returns a list of results. I hope this helps for your use case.

**Comment by rswgnu** [comment]
Thanks, Daniel.  That is a start.  What I want is a single name narrowed
via completion for use in a link which I can then send to osm-search later
to display in the map.  -- rsw

**Comment by minad** [comment]
Sure, just pass the results from `osm--search` to completing-read. Alternatively just take the first match?

**Comment by rswgnu** [comment]
Okay, thanks.
