### ISSUE TITLE
What is osm-ol? I am getting an error related to it

### ISSUE THREAD

**Issue by OrionRandD** [minad/osm#43]
*messages*
Error (use-package): osm/:init: Cannot open load file: No such file or directory, osm-ol

**Comment by minad** [comment]
It has been integrated into osm.el. See the updated configuration: https://github.com/minad/osm#configuration

**Comment by OrionRandD** [comment]
> It has been integrated into osm.el. See the updated configuration: https://github.com/minad/osm#configuration

OK.  I have deleted the package and installed again through MELPA, but the error persists...
What should I do then? Thx.

**Comment by minad** [comment]
The `(require 'osm-ol)` should be removed from your configuration.
